name: Build Swagger UI

on:
  pull_request:
  push:
    branches:
      - main


jobs:
  build:
    name: Build and Deploy Swagger UI in Github Page
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate Swagger UI

        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: mastodon-openapi.yaml
          version: 5.0.0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
